modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
    config = "freeterraforged-common.mixins.json"

[[mixins]]
    config = "freeterraforged-neoforge.mixins.json"

[[mods]]
    modId="freeterraforged"
    displayName="FreeTerraForged"
    version="${version}"
    authors="dags,Won-Ton,racoonman2,psiber,squinch"
    credits="raccoonman and the wider TerraForged community, in all its past and present iterations."
    logoFile="logo.png"
    displayURL="https://github.com/etcodehome/freeterraforged/"
    issueTrackerURL="https://github.com/etcodehome/freeterraforged/issues"
    description="FreeTerraForged is a community-driven fork of ReTerraForged for modern Minecraft, providing highly customizable Overworld terrain generation and continuing the TerraForged lineage."

[[dependencies.freeterraforged]]
    modId="neoforge"
    mandatory=true
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.freeterraforged]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.21.1,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.freeterraforged]]
    modId = "reterraforged"
    type = "incompatible"
    reason = "ReTerraForged and FreeTerraForged cannot run together."
    versionRange = "*"
    ordering = "NONE"
    side = "BOTH"
