package etcodehome.freeterraforged.world.worldgen.runtime;

public enum WorldgenFacet {
	BIOME_COMPOSITION,
	PROVIDER_SELECTION,
	SELECTION_DECORATION,
	SPATIAL_OWNERSHIP,
	SAMPLER_DECORATION,
	DENSITY_SETTINGS,
	SURFACE,
	CARVERS,
	PLACED_FEATURES,
	STRUCTURES
}
